### ISSUE TITLE
Pixbuf data was changed during execution. 

### ISSUE THREAD

**Issue by kojix2** [red-data-tools/red-datasets-gdk-pixbuf#4]
Hello. 
This may not be a problem of red-datasets-gdk-pixbuf. 
I can not isolate the cause of the problem, so I will report it here. 

### step to reproduce
```ruby
require 'datasets-gdk-pixbuf'
require 'gtk3'
require 'fileutils'

FileUtils.mkdir_p("cifar_before")
FileUtils.mkdir_p("cifar_after")

w = Gtk::Window.new
w.set_size_request 300, 200
flowbox = Gtk::FlowBox.new 

images = []

cifar = Datasets::CIFAR.new
cifar.take(70).each_with_index do |record, i|
  pixbuf = record.to_gdk_pixbuf
  images << Gtk::Image.new(pixbuf: pixbuf)
  flowbox.add images.last
  images.last.pixbuf.save("cifar_before/#{i}.png")
end

images.each_with_index do |im, i|
  im.pixbuf.save("cifar_after/#{i}.png")
end

w.add flowbox
w.show_all
w.signal_connect(:destroy){Gtk.main_quit}
Gtk.main
```

### Actual behavior
* Images loaded early look strange.
![screenshot](https://user-images.githubusercontent.com/5798442/49859914-0d557f80-fe3c-11e8-843d-872117229808.png)

* images are all right when they are loaded. 
![screenshot2](https://user-images.githubusercontent.com/5798442/49860734-c10b3f00-fe3d-11e8-8bb9-8b7d8c8a40e5.png)

* The pixbuf data of GtkImage is broken. ?
![screenshot1](https://user-images.githubusercontent.com/5798442/49860758-cbc5d400-fe3d-11e8-8ca1-ef1619906468.png)

### Expected behavior
I did the same thing with generated data. It works as expected. I don't know why. 

```ruby
require 'numo/narray'
require 'gtk3'
require 'fileutils'

FileUtils.mkdir_p "hoge_before"
FileUtils.mkdir_p "hoge_after"

w = Gtk::Window.new
w.set_size_request 300, 200
flowbox = Gtk::FlowBox.new 

images = []

64.times do |i|
  d = Numo::UInt8.new(32,32,1).fill(255-i*2)
  z = d.new_zeros
  data = Numo::UInt8.dstack([z,d,z]).to_string
  pixbuf = Gdk::Pixbuf.new(data: data, width:32, height:32)
  images << Gtk::Image.new(pixbuf: pixbuf)
  flowbox.add images.last
  images.last.pixbuf.save("hoge_before/#{i}.png")
end

images.each_with_index do |im, i|
  im.pixbuf.save("hoge_after/#{i}.png")
end

w.add flowbox
w.show_all
w.signal_connect(:destroy){Gtk.main_quit}
Gtk.main
```
![screenshot](https://user-images.githubusercontent.com/5798442/49861463-3aeff800-fe3f-11e8-9756-11bde6cf428e.png)

### environment
* Ubuntu 18.10
* Ruby 2.5.3p105
* gtk3 (3.3.0) 
* red-datasets-gdk-pixbuf (0.0.3)
gtk3, red-datasets-gdk-pixbuf are installed `gem install` command. not latest github master. 
* libgtk 3.24.1-ubuntu2

**Comment by kojix2** [comment]
Additional notes

The following can cause problems.

edit red-datasets-gdk-pixbuf/libcifar.rb
```ruby 
require "gdk_pixbuf2"
require 'numpy'
require 'numo/narray'

module DatasetsGdkPixbuf
  module CIFARPixbufable
    def to_gdk_pixbuf
      width = 32
      height = 32
      color_size = width * height
      rgb_data = pixels.each_slice(color_size).to_a.transpose.flatten

#    y = Numo::UInt8[*rgb_data]
      y = Numo::UInt8.new(32,32,3).rand(100,102)
      data2 = y.to_string

#       data1 = rgb_data.pack("C*")

#       I tried using numpy gem of Murata, but nothing changed.
#       x = Numpy.asarray(rgb_data, dtype: :uint8)
#       data3 = x.tostring()

      GdkPixbuf::Pixbuf.new(:data => data2,
                            :width => width,
                            :height => height)
    end
  end
end

module Datasets
  class CIFAR
    class Record10
      include DatasetsGdkPixbuf::CIFARPixbufable
    end

    class Record100
      include DatasetsGdkPixbuf::CIFARPixbufable
    end
  end
end
```

hoge.rb
```ruby
require 'datasets-gdk-pixbuf'
require 'gtk3'
require 'fileutils'

FileUtils.mkdir_p("cifar_before")
FileUtils.mkdir_p("cifar_after")

w = Gtk::Window.new
w.set_size_request 300, 200
flowbox = Gtk::FlowBox.new 

images = []

cifar = Datasets::CIFAR.new
cifar.take(49).each_with_index do |record, i|
  pixbuf = record.to_gdk_pixbuf
  images << Gtk::Image.new(pixbuf: pixbuf)
  flowbox.add images.last
  images.last.pixbuf.save("cifar_before/#{i}.png")
end

images.each_with_index do |im, i|
  im.pixbuf.save("cifar_after/#{i}.png")
end

w.add flowbox
w.show_all
w.signal_connect(:destroy){Gtk.main_quit}
Gtk.main
```

![screenshot](https://user-images.githubusercontent.com/5798442/50049995-bac5dd00-0133-11e9-893c-24e9ba13de48.png)

The saved images are different from the images displayed in the Gtk window. This is not because I ran scripts many times and submitted screenshots of another time. The two captured images are obtained at the same time.

![screenshot2](https://user-images.githubusercontent.com/5798442/50050011-06788680-0134-11e9-9a27-448461c75ab1.png)

Ok. Now I think I can reproduce the error with generated data. 
Therefore, the process of generating data is not a problem. 
But surprisingly, the following code does not reproduce the problem.

hoge2.rb
```ruby
require 'numo/narray'
require 'gtk3'
require 'fileutils'

FileUtils.mkdir_p "hoge_before"
FileUtils.mkdir_p "hoge_after"

w = Gtk::Window.new
w.set_size_request 300, 200
flowbox = Gtk::FlowBox.new 

images = []

70.times do |i|
  nar = Numo::UInt8.new(32,32,3).rand(100,102)
  data2 = nar.to_string
  pixbuf = Gdk::Pixbuf.new(data: data2, width:32, height:32)
  images << Gtk::Image.new(pixbuf: pixbuf)
  flowbox.add images.last
  images.last.pixbuf.save("hoge_before/#{i}.png")
end

images.each_with_index do |im, i|
  im.pixbuf.save("hoge_after/#{i}.png")
end

w.add flowbox
w.show_all
w.signal_connect(:destroy){Gtk.main_quit}
Gtk.main
```
![screenshot](https://user-images.githubusercontent.com/5798442/50050150-a0d9c980-0136-11e9-88c6-3f69b79eaef5.png)

very strange...

Another new finding.
Everyone who is interested in this repository is a cat, except me.
![fuga](https://user-images.githubusercontent.com/5798442/50050402-4728cd80-013d-11e9-92b4-0d1f41f0b016.png)

**Comment by kou** [comment]
I think that it has been already fixed in gdk_pixbuf2 master.

**Comment by kojix2** [comment]
You're right.
I'm sorry. m(_ _)m 
Next time I will check the latest version.
